import streamlit as st

st.set_page_config(
    page_title="NCV Assistant",
    page_icon="🧠",
    layout="wide"
)

st.title("🧠 Nerve Conduction Velocity (NCV) Assistant")

st.warning(
    "⚠️ Educational Tool Only. This assistant does not diagnose diseases. "
    "All findings should be interpreted by a qualified physician."
)

st.divider()

st.header("⚡ Motor Nerve Conduction Study")

motor_nerve = st.selectbox(
    "Select Motor Nerve",
    [
        "Median Nerve",
        "Ulnar Nerve",
        "Peroneal Nerve",
        "Tibial Nerve"
    ]
)

col1, col2 = st.columns(2)

with col1:
    distal_latency = st.number_input(
        "Distal Latency (ms)",
        min_value=0.0,
        value=0.0,
        step=0.1
    )

    cmap = st.number_input(
        "CMAP Amplitude (mV)",
        min_value=0.0,
        value=0.0,
        step=0.1
    )

with col2:
    velocity = st.number_input(
        "Conduction Velocity (m/s)",
        min_value=0.0,
        value=0.0,
        step=0.1
    )

    duration = st.number_input(
        "CMAP Duration (ms)",
        min_value=0.0,
        value=0.0,
        step=0.1
    )

st.divider()

with st.expander("🅰️ Distal Latency (DL)"):

    st.markdown("""
### ⚡ What is Distal Latency?

Distal Latency is the time required for an electrical impulse to travel
from the stimulation point to the muscle.

### 🎯 Importance

• Detects distal nerve slowing

• Helps identify entrapment neuropathies

• Assesses myelin integrity

### Typical Normal Values

• Median ≤ 4.2 ms

• Ulnar ≤ 3.5 ms

• Tibial ≤ 6.0 ms

• Peroneal ≤ 6.5 ms

### If Prolonged

Possible educational associations

• Carpal Tunnel Syndrome

• Cubital Tunnel Syndrome

• Demyelinating Neuropathy

• Peripheral Nerve Compression

### If Short

Usually not clinically significant.

### Clinical Significance

Prolonged distal latency usually indicates slowing across the distal segment
of the nerve.

Always interpret together with CMAP amplitude and conduction velocity.
""")

st.divider()

with st.expander("🅱️ CMAP Amplitude"):

    st.markdown("""
### ⚡ What is CMAP?

Compound Muscle Action Potential (CMAP) represents the electrical response
generated by muscle fibers after motor nerve stimulation.

### 🎯 Importance

• Estimates functioning motor axons

• Helps differentiate axonal and demyelinating neuropathy

### Typical Normal

Normal values vary according to nerve and laboratory.

### If Reduced

Possible educational associations

• Axonal Neuropathy

• Severe Nerve Injury

• Motor Neuron Disease

• Advanced Compression Neuropathy

### If Increased

May occur due to collateral reinnervation after chronic nerve injury.

### Clinical Significance

Low CMAP amplitude usually reflects axonal loss.

Interpret together with distal latency and conduction velocity.
""")

st.divider()

with st.expander("🅲 Motor Conduction Velocity"):

    st.markdown("""
### ⚡ What is Motor Conduction Velocity?

Measures the speed of electrical impulse transmission along the motor nerve.

### 🎯 Importance

Reflects myelin integrity.

### Typical Normal Values

Upper Limb

50–65 m/s

Lower Limb

40–55 m/s

### If Reduced

Possible educational associations

• Demyelinating Neuropathy

• Guillain-Barre Syndrome

• CIDP

• Diabetic Neuropathy

• Peripheral Neuropathy

### If Increased

Usually not clinically significant.

### Clinical Significance

Reduced conduction velocity is one of the strongest indicators of myelin damage.

Temperature may influence conduction velocity.
""")

st.divider()

with st.expander("🅳 CMAP Duration"):

    st.markdown("""
### ⚡ What is CMAP Duration?

CMAP duration measures the total time over which the muscle action potential
is recorded.

### 🎯 Importance

Helps evaluate temporal dispersion.

### If Prolonged

Possible educational associations

• Demyelination

• Temporal Dispersion

• Conduction Abnormality

### If Short

Usually not clinically significant.

### Clinical Significance

Prolonged duration may indicate desynchronization of nerve conduction.
""")

st.divider()

if st.button("Generate Motor NCV Educational Interpretation"):

    st.subheader("📋 Educational Summary")

    if distal_latency > 4.2:
        st.warning("⚠️ Distal latency is prolonged. This may be associated with distal nerve slowing or entrapment neuropathy.")

    else:
        st.success("✅ Distal latency is within the expected range.")

    if cmap < 5:
        st.warning("⚠️ CMAP amplitude is reduced. This may suggest axonal involvement.")

    else:
        st.success("✅ CMAP amplitude appears preserved.")

    if velocity < 50:
        st.warning("⚠️ Conduction velocity is reduced. This may indicate demyelination or peripheral neuropathy.")

    else:
        st.success("✅ Conduction velocity is within the expected range.")

    st.info(
        "This interpretation is educational only and should always be correlated "
        "with the patient's symptoms, examination findings, and the complete NCV study."
    )
#-----------
st.divider()

st.header("📘 Motor NCV Educational Information")

# ---------------- DISTAL LATENCY ---------------- #

with st.expander("🅰️ Distal Latency (DL) - Complete Information"):

    st.markdown("""
### ⚡ What is Distal Latency?

Distal Latency (DL) is the time required for an electrical impulse to travel
from the stimulation site to the muscle.

### 🎯 Importance

• Detects distal nerve conduction slowing

• Helps diagnose entrapment neuropathies

• Evaluates myelin integrity

• Useful for early neuropathy detection

### 🧠 Clinical Significance

A prolonged distal latency usually indicates slowing of nerve conduction
across the distal segment.

### 📌 If Prolonged

Possible Educational Associations

• Carpal Tunnel Syndrome

• Cubital Tunnel Syndrome

• Tarsal Tunnel Syndrome

• Demyelinating Neuropathy

• Chronic Nerve Compression

### 📌 If Normal

Usually indicates preserved distal nerve conduction.

### 📌 If Short

Generally not clinically significant.

### 💡 Interpretation Tip

Interpret together with:

• CMAP Amplitude

• Conduction Velocity

• F-wave
""")

# ---------------- CMAP ---------------- #

with st.expander("🅱️ CMAP Amplitude - Complete Information"):

    st.markdown("""
### ⚡ What is CMAP?

Compound Muscle Action Potential (CMAP) is the electrical response recorded
from a muscle after stimulation of its motor nerve.

### 🎯 Importance

• Reflects functioning motor axons

• Helps differentiate axonal vs demyelinating lesions

• Estimates severity of nerve injury

### 🧠 Clinical Significance

Lower CMAP usually reflects axonal loss.

### 📌 If Reduced

Possible Educational Associations

• Axonal Neuropathy

• Severe Compression Neuropathy

• Peripheral Nerve Injury

• Motor Neuron Disease

• Advanced Diabetic Neuropathy

### 📌 If Normal

Motor axonal function is generally preserved.

### 📌 If Increased

May occur after chronic reinnervation.

### 💡 Interpretation Tip

Never interpret CMAP alone.

Always correlate with

• Distal Latency

• Velocity

• Needle EMG
""")

# ---------------- VELOCITY ---------------- #

with st.expander("🅲 Motor Conduction Velocity - Complete Information"):

    st.markdown("""
### ⚡ What is Conduction Velocity?

Measures the speed of electrical impulse transmission through a motor nerve.

### 🎯 Importance

• Best indicator of myelin health

• Detects demyelination

• Useful for polyneuropathy evaluation

### Typical Normal

Upper Limb

50–65 m/s

Lower Limb

40–55 m/s

### 🧠 Clinical Significance

Reduced velocity indicates slowing of nerve impulse conduction.

### 📌 If Reduced

Possible Educational Associations

• Peripheral Neuropathy

• Demyelinating Neuropathy

• Guillain-Barre Syndrome

• CIDP

• Hereditary Neuropathy

### 📌 If Normal

Usually suggests intact myelin.

### 📌 If Increased

Usually no clinical significance.

### 💡 Interpretation Tip

Cold limbs can artificially reduce conduction velocity.
""")

# ---------------- DURATION ---------------- #

with st.expander("🅳 CMAP Duration - Complete Information"):

    st.markdown("""
### ⚡ What is CMAP Duration?

Represents the total time occupied by the compound muscle action potential.

### 🎯 Importance

• Detects temporal dispersion

• Helps identify demyelination

• Supports interpretation of conduction block

### 🧠 Clinical Significance

Long duration indicates desynchronization of nerve fiber conduction.

### 📌 If Prolonged

Possible Educational Associations

• Demyelinating Neuropathy

• Temporal Dispersion

• Chronic Compression

### 📌 If Normal

Synchronous motor fiber activation.

### 📌 If Short

Usually not clinically significant.

### 💡 Interpretation Tip

Always correlate with latency and conduction velocity.
""")

st.divider()

st.info("""
🧠 **Educational Note**

Motor NCV should never be interpreted using only one parameter.

Accurate interpretation requires correlation between:

• Distal Latency

• CMAP Amplitude

• Conduction Velocity

• CMAP Duration

• Clinical Symptoms

• Needle EMG Findings (when available)

Final interpretation should always be performed by a qualified Neurologist,
Physiatrist, or Electrodiagnostic Physician.
""")
#---------
st.divider()

st.header("⚡ Sensory Nerve Conduction Study (SNCV)")

sensory_nerve = st.selectbox(
    "Select Sensory Nerve",
    [
        "Median Sensory",
        "Ulnar Sensory",
        "Radial Sensory",
        "Sural Nerve",
        "Superficial Peroneal"
    ]
)

col1, col2 = st.columns(2)

with col1:
    sensory_latency = st.number_input(
        "Peak Latency (ms)",
        min_value=0.0,
        value=0.0,
        step=0.1,
        key="sl"
    )

    snap_amplitude = st.number_input(
        "SNAP Amplitude (µV)",
        min_value=0.0,
        value=0.0,
        step=0.1,
        key="sa"
    )

with col2:
    sensory_velocity = st.number_input(
        "Conduction Velocity (m/s)",
        min_value=0.0,
        value=0.0,
        step=0.1,
        key="sv"
    )

st.divider()

with st.expander("🅰️ Peak Latency (Sensory) - Complete Information"):

    st.markdown("""
### ⚡ What is Peak Latency?

Peak latency is the time required for a sensory nerve impulse to travel
from the stimulation point to the recording electrode.

### 🎯 Importance

• Detects distal sensory nerve slowing

• Useful for early entrapment neuropathy

• Sensitive marker of demyelination

### If Prolonged

Possible Educational Associations

• Carpal Tunnel Syndrome

• Cubital Tunnel Syndrome

• Peripheral Neuropathy

• Demyelinating Neuropathy

### If Normal

Usually indicates preserved sensory conduction.

### Clinical Significance

Latency prolongation often represents slowing of the fastest sensory fibers.

### 💡 Tip

Interpret together with SNAP amplitude and conduction velocity.
""")

with st.expander("🅱️ SNAP Amplitude - Complete Information"):

    st.markdown("""
### ⚡ What is SNAP?

Sensory Nerve Action Potential (SNAP) represents the electrical activity
generated by sensory nerve fibers.

### 🎯 Importance

• Reflects sensory axonal integrity

• Estimates severity of sensory nerve damage

### If Reduced

Possible Educational Associations

• Axonal Neuropathy

• Diabetic Neuropathy

• Peripheral Nerve Injury

• Severe Compression

### If Absent

May indicate severe sensory axonal loss.

### Clinical Significance

Reduced SNAP amplitude generally reflects axonal degeneration.

### 💡 Tip

Amplitude alone should never be used for interpretation.
""")

with st.expander("🅲 Sensory Conduction Velocity - Complete Information"):

    st.markdown("""
### ⚡ What is Sensory Conduction Velocity?

Measures the speed of impulse transmission through sensory nerves.

### 🎯 Importance

• Evaluates myelin integrity

• Detects sensory neuropathy

• Useful in generalized polyneuropathy

### Normal

Usually greater than 50 m/s in upper limb nerves.

### If Reduced

Possible Educational Associations

• Demyelinating Neuropathy

• Peripheral Neuropathy

• Diabetic Neuropathy

• Entrapment Neuropathy

### Clinical Significance

Reduced sensory velocity indicates slowing of sensory conduction.

### 💡 Tip

Cold limbs may falsely reduce sensory conduction velocity.
""")

st.divider()

if st.button("Generate Sensory NCV Educational Interpretation"):

    st.subheader("📋 Sensory NCV Summary")

    if sensory_latency > 3.5:
        st.warning("⚠️ Sensory latency is prolonged. Educationally this may indicate distal sensory nerve slowing.")

    else:
        st.success("✅ Sensory latency appears within expected limits.")

    if snap_amplitude < 10:
        st.warning("⚠️ SNAP amplitude is reduced. This may suggest sensory axonal involvement.")

    else:
        st.success("✅ SNAP amplitude appears preserved.")

    if sensory_velocity < 50:
        st.warning("⚠️ Sensory conduction velocity is reduced. Educationally this may indicate demyelination or peripheral neuropathy.")

    else:
        st.success("✅ Sensory conduction velocity appears within expected limits.")

    st.info("""
This interpretation is educational only.

Final interpretation should always be based on:

• Clinical history

• Physical examination

• Complete NCV study

• Needle EMG (when available)

• Physician's opinion
""")
  #--------
st.divider()

st.header("⚡ F-wave Study")

f_wave_latency = st.number_input(
    "F-wave Minimum Latency (ms)",
    min_value=0.0,
    value=0.0,
    step=0.1,
    key="fw_latency"
)

f_wave_status = st.selectbox(
    "F-wave Response",
    [
        "Normal",
        "Prolonged",
        "Absent"
    ],
    key="fw_status"
)

with st.expander("🅳 F-wave - Complete Information"):

    st.markdown("""
### ⚡ What is F-wave?

F-wave is a late motor response produced when an electrical impulse travels
from the stimulation site to the spinal cord and back to the muscle.

### 🎯 Importance

• Evaluates proximal nerve segments

• Detects root lesions

• Detects generalized neuropathy

• Useful in early Guillain-Barre Syndrome

### If Prolonged

Possible Educational Associations

• Demyelinating Neuropathy

• Radiculopathy

• Peripheral Neuropathy

### If Absent

Possible Educational Associations

• Severe Neuropathy

• Guillain-Barre Syndrome

• Proximal Nerve Lesion

### Clinical Significance

F-wave abnormalities usually indicate proximal conduction abnormalities.

### 💡 Tip

Always interpret together with Motor NCV.
""")

st.divider()

st.header("⚡ H-reflex Study")

h_latency = st.number_input(
    "H-reflex Latency (ms)",
    min_value=0.0,
    value=0.0,
    step=0.1,
    key="hreflex_latency"
)

h_status = st.selectbox(
    "H-reflex Response",
    [
        "Normal",
        "Delayed",
        "Absent"
    ],
    key="hreflex_status"
)

with st.expander("🅴 H-reflex - Complete Information"):

    st.markdown("""
### ⚡ What is H-reflex?

The H-reflex is an electrically elicited monosynaptic reflex similar to the
ankle jerk reflex.

### 🎯 Importance

• Evaluates S1 nerve root

• Evaluates tibial nerve

• Useful in radiculopathy

• Useful in polyneuropathy

### If Delayed

Possible Educational Associations

• S1 Radiculopathy

• Tibial Neuropathy

• Peripheral Neuropathy

### If Absent

Possible Educational Associations

• Severe S1 Root Lesion

• Polyneuropathy

• Tibial Nerve Dysfunction

### Clinical Significance

Delayed or absent H-reflex may indicate proximal nerve dysfunction.

### 💡 Tip

Interpret with clinical examination and F-wave findings.
""")

st.divider()

if st.button("Generate Overall NCV Educational Summary"):

    st.subheader("🧠 Overall Educational Interpretation")

    findings = []

    # Motor
    if distal_latency > 4.2:
        findings.append(
            "• Distal latency is prolonged, suggesting slowing across the distal motor nerve segment."
        )

    if cmap < 5:
        findings.append(
            "• CMAP amplitude is reduced, which may indicate motor axonal involvement."
        )

    if velocity < 50:
        findings.append(
            "• Motor conduction velocity is reduced, suggesting possible demyelinating involvement."
        )

    # Sensory
    if sensory_latency > 3.5:
        findings.append(
            "• Sensory latency is prolonged, indicating delayed sensory conduction."
        )

    if snap_amplitude < 10:
        findings.append(
            "• SNAP amplitude is reduced, suggesting sensory axonal involvement."
        )

    if sensory_velocity < 50:
        findings.append(
            "• Sensory conduction velocity is reduced."
        )

    # F-wave
    if f_wave_status == "Prolonged":
        findings.append(
            "• F-wave latency is prolonged, suggesting proximal nerve involvement."
        )

    elif f_wave_status == "Absent":
        findings.append(
            "• F-wave response is absent, which may occur in severe neuropathy or proximal nerve lesions."
        )

    # H-reflex
    if h_status == "Delayed":
        findings.append(
            "• H-reflex is delayed, which may indicate S1 radiculopathy."
        )

    elif h_status == "Absent":
        findings.append(
            "• H-reflex is absent, which may occur in severe S1 root lesions or polyneuropathy."
        )

    if len(findings) == 0:
        st.success(
            "✅ No major educational abnormalities detected from the entered values."
        )

    else:
        for item in findings:
            st.write(item)

    st.divider()

    st.subheader("📚 Possible Educational Associations")

    conditions = []

    if distal_latency > 4.2:
        conditions.append("• Carpal Tunnel Syndrome")
        conditions.append("• Entrapment Neuropathy")

    if velocity < 50:
        conditions.append("• Demyelinating Neuropathy")
        conditions.append("• Chronic Inflammatory Demyelinating Polyneuropathy (CIDP)")
        conditions.append("• Guillain-Barre Syndrome")

    if cmap < 5:
        conditions.append("• Axonal Neuropathy")
        conditions.append("• Peripheral Nerve Injury")

    if snap_amplitude < 10:
        conditions.append("• Sensory Axonal Neuropathy")

    if h_status == "Delayed":
        conditions.append("• S1 Radiculopathy")

    if f_wave_status == "Absent":
        conditions.append("• Proximal Nerve Dysfunction")

    if len(conditions) == 0:
        st.success("No specific educational associations identified.")

    else:
        for c in sorted(set(conditions)):
            st.write(c)

    st.divider()

    st.info("""
⚠️ **Educational Disclaimer**

This NCV Assistant is intended for education and learning purposes only.

It does not diagnose diseases or replace a neurologist, physiatrist,
or electrodiagnostic physician.

Final interpretation should always consider:

• Clinical symptoms

• Physical examination

• Complete NCV study

• Needle EMG findings

• Laboratory investigations (when appropriate)

• Physician's expert opinion
""")
  #---------
# ===========================
# NCV REPORT ANALYSIS
# ===========================

st.divider()

if st.button("🔍 Analyze NCV Report"):

    st.header("🧠 NCV Report Analysis")

    # ------------------------
    # DISTAL LATENCY
    # ------------------------

    if distal_latency > 0:

        if distal_latency <= 4.2:
            st.success(f"✅ Distal Latency : {distal_latency} ms → Normal")

        elif distal_latency <= 5.5:
            st.warning(f"🟡 Distal Latency : {distal_latency} ms → Mildly Prolonged")

        else:
            st.error(f"🔴 Distal Latency : {distal_latency} ms → Significantly Prolonged")


    # ------------------------
    # CMAP
    # ------------------------

    if cmap > 0:

        if cmap >= 5:
            st.success(f"✅ CMAP Amplitude : {cmap} mV → Normal")

        elif cmap >= 2:
            st.warning(f"🟡 CMAP Amplitude : {cmap} mV → Mildly Reduced")

        else:
            st.error(f"🔴 CMAP Amplitude : {cmap} mV → Severely Reduced")


    # ------------------------
    # VELOCITY
    # ------------------------

    if velocity > 0:

        if velocity >= 50:
            st.success(f"✅ Motor Conduction Velocity : {velocity} m/s → Normal")

        elif velocity >= 40:
            st.warning(f"🟡 Motor Conduction Velocity : {velocity} m/s → Mild Slowing")

        else:
            st.error(f"🔴 Motor Conduction Velocity : {velocity} m/s → Significant Slowing")


    # ------------------------
    # SENSORY LATENCY
    # ------------------------

    if sensory_latency > 0:

        if sensory_latency <= 3.5:
            st.success(f"✅ Sensory Latency : {sensory_latency} ms → Normal")

        elif sensory_latency <= 4.5:
            st.warning(f"🟡 Sensory Latency : {sensory_latency} ms → Mildly Prolonged")

        else:
            st.error(f"🔴 Sensory Latency : {sensory_latency} ms → Prolonged")


    # ------------------------
    # SNAP
    # ------------------------

    if snap_amplitude > 0:

        if snap_amplitude >= 10:
            st.success(f"✅ SNAP Amplitude : {snap_amplitude} µV → Normal")

        elif snap_amplitude >= 5:
            st.warning(f"🟡 SNAP Amplitude : {snap_amplitude} µV → Mildly Reduced")

        else:
            st.error(f"🔴 SNAP Amplitude : {snap_amplitude} µV → Severely Reduced")


    # ------------------------
    # SENSORY VELOCITY
    # ------------------------

    if sensory_velocity > 0:

        if sensory_velocity >= 50:
            st.success(f"✅ Sensory Conduction Velocity : {sensory_velocity} m/s → Normal")

        elif sensory_velocity >= 40:
            st.warning(f"🟡 Sensory Conduction Velocity : {sensory_velocity} m/s → Mild Slowing")

        else:
            st.error(f"🔴 Sensory Conduction Velocity : {sensory_velocity} m/s → Significant Slowing")


    # ------------------------
    # F-WAVE
    # ------------------------

    if f_wave_status == "Normal":
        st.success("✅ F-wave → Normal")

    elif f_wave_status == "Prolonged":
        st.warning("🟡 F-wave → Prolonged")

    elif f_wave_status == "Absent":
        st.error("🔴 F-wave → Absent")


    # ------------------------
    # H-REFLEX
    # ------------------------

    if h_status == "Normal":
        st.success("✅ H-reflex → Normal")

    elif h_status == "Delayed":
        st.warning("🟡 H-reflex → Delayed")

    elif h_status == "Absent":
        st.error("🔴 H-reflex → Absent")

    # ===========================
    # OVERALL SUMMARY
    # ===========================

    st.divider()

    st.subheader("🩺 Overall NCV Summary")

    severe = False
    mild = False

    if distal_latency > 5.5:
        severe = True
    elif distal_latency > 4.2:
        mild = True

    if cmap < 2:
        severe = True
    elif cmap < 5:
        mild = True

    if velocity < 40:
        severe = True
    elif velocity < 50:
        mild = True

    if sensory_latency > 4.5:
        severe = True
    elif sensory_latency > 3.5:
        mild = True

    if snap_amplitude < 5:
        severe = True
    elif snap_amplitude < 10:
        mild = True

    if sensory_velocity < 40:
        severe = True
    elif sensory_velocity < 50:
        mild = True

    if f_wave_status == "Absent":
        severe = True
    elif f_wave_status == "Prolonged":
        mild = True

    if h_status == "Absent":
        severe = True
    elif h_status == "Delayed":
        mild = True

    if severe:
        st.error("🔴 Overall Educational Interpretation: Multiple significant NCV abnormalities are present.")
        st.info("Educational possibilities include demyelinating neuropathy, axonal neuropathy, entrapment neuropathy, radiculopathy, or generalized peripheral neuropathy. Correlate with clinical findings and physician interpretation.")

    elif mild:
        st.warning("🟡 Overall Educational Interpretation: Mild NCV abnormalities are present.")
        st.info("These findings may represent early neuropathy, mild entrapment neuropathy, or borderline conduction abnormalities. Clinical correlation is recommended.")

    else:
        st.success("🟢 Overall Educational Interpretation: The entered NCV values are within the common reference ranges.")
        st.info("Normal NCV does not completely exclude neurological disorders. Interpretation should always consider symptoms, examination, and when appropriate, Needle EMG findings.")
