import streamlit as st

st.set_page_config(
    page_title="NCV Assistant",
    page_icon="🧠",
    layout="wide"
)

st.title("🧠 Nerve Conduction Velocity (NCV) Assistant")

st.warning(
    "⚠️ Educational Tool Only. This assistant does not diagnose diseases. "
    "All findings should be interpreted by a qualified physician."
)

st.divider()

st.header("⚡ Motor Nerve Conduction Study")

motor_nerve = st.selectbox(
    "Select Motor Nerve",
    [
        "Median Nerve",
        "Ulnar Nerve",
        "Peroneal Nerve",
        "Tibial Nerve"
    ]
)

col1, col2 = st.columns(2)

with col1:
    distal_latency = st.number_input(
        "Distal Latency (ms)",
        min_value=0.0,
        value=0.0,
        step=0.1
    )

    cmap = st.number_input(
        "CMAP Amplitude (mV)",
        min_value=0.0,
        value=0.0,
        step=0.1
    )

with col2:
    velocity = st.number_input(
        "Conduction Velocity (m/s)",
        min_value=0.0,
        value=0.0,
        step=0.1
    )

    duration = st.number_input(
        "CMAP Duration (ms)",
        min_value=0.0,
        value=0.0,
        step=0.1
    )

st.divider()

with st.expander("🅰️ Distal Latency (DL)"):

    st.markdown("""
### ⚡ What is Distal Latency?

Distal Latency is the time required for an electrical impulse to travel
from the stimulation point to the muscle.

### 🎯 Importance

• Detects distal nerve slowing

• Helps identify entrapment neuropathies

• Assesses myelin integrity

### Typical Normal Values

• Median ≤ 4.2 ms

• Ulnar ≤ 3.5 ms

• Tibial ≤ 6.0 ms

• Peroneal ≤ 6.5 ms

### If Prolonged

Possible educational associations

• Carpal Tunnel Syndrome

• Cubital Tunnel Syndrome

• Demyelinating Neuropathy

• Peripheral Nerve Compression

### If Short

Usually not clinically significant.

### Clinical Significance

Prolonged distal latency usually indicates slowing across the distal segment
of the nerve.

Always interpret together with CMAP amplitude and conduction velocity.
""")

st.divider()

with st.expander("🅱️ CMAP Amplitude"):

    st.markdown("""
### ⚡ What is CMAP?

Compound Muscle Action Potential (CMAP) represents the electrical response
generated by muscle fibers after motor nerve stimulation.

### 🎯 Importance

• Estimates functioning motor axons

• Helps differentiate axonal and demyelinating neuropathy

### Typical Normal

Normal values vary according to nerve and laboratory.

### If Reduced

Possible educational associations

• Axonal Neuropathy

• Severe Nerve Injury

• Motor Neuron Disease

• Advanced Compression Neuropathy

### If Increased

May occur due to collateral reinnervation after chronic nerve injury.

### Clinical Significance

Low CMAP amplitude usually reflects axonal loss.

Interpret together with distal latency and conduction velocity.
""")

st.divider()

with st.expander("🅲 Motor Conduction Velocity"):

    st.markdown("""
### ⚡ What is Motor Conduction Velocity?

Measures the speed of electrical impulse transmission along the motor nerve.

### 🎯 Importance

Reflects myelin integrity.

### Typical Normal Values

Upper Limb

50–65 m/s

Lower Limb

40–55 m/s

### If Reduced

Possible educational associations

• Demyelinating Neuropathy

• Guillain-Barre Syndrome

• CIDP

• Diabetic Neuropathy

• Peripheral Neuropathy

### If Increased

Usually not clinically significant.

### Clinical Significance

Reduced conduction velocity is one of the strongest indicators of myelin damage.

Temperature may influence conduction velocity.
""")

st.divider()

with st.expander("🅳 CMAP Duration"):

    st.markdown("""
### ⚡ What is CMAP Duration?

CMAP duration measures the total time over which the muscle action potential
is recorded.

### 🎯 Importance

Helps evaluate temporal dispersion.

### If Prolonged

Possible educational associations

• Demyelination

• Temporal Dispersion

• Conduction Abnormality

### If Short

Usually not clinically significant.

### Clinical Significance

Prolonged duration may indicate desynchronization of nerve conduction.
""")

st.divider()

if st.button("Generate Motor NCV Educational Interpretation"):

    st.subheader("📋 Educational Summary")

    if distal_latency > 4.2:
        st.warning("⚠️ Distal latency is prolonged. This may be associated with distal nerve slowing or entrapment neuropathy.")

    else:
        st.success("✅ Distal latency is within the expected range.")

    if cmap < 5:
        st.warning("⚠️ CMAP amplitude is reduced. This may suggest axonal involvement.")

    else:
        st.success("✅ CMAP amplitude appears preserved.")

    if velocity < 50:
        st.warning("⚠️ Conduction velocity is reduced. This may indicate demyelination or peripheral neuropathy.")

    else:
        st.success("✅ Conduction velocity is within the expected range.")

    st.info(
        "This interpretation is educational only and should always be correlated "
        "with the patient's symptoms, examination findings, and the complete NCV study."
    )
#-----------
st.divider()

st.header("📘 Motor NCV Educational Information")

# ---------------- DISTAL LATENCY ---------------- #

with st.expander("🅰️ Distal Latency (DL) - Complete Information"):

    st.markdown("""
### ⚡ What is Distal Latency?

Distal Latency (DL) is the time required for an electrical impulse to travel
from the stimulation site to the muscle.

### 🎯 Importance

• Detects distal nerve conduction slowing

• Helps diagnose entrapment neuropathies

• Evaluates myelin integrity

• Useful for early neuropathy detection

### 🧠 Clinical Significance

A prolonged distal latency usually indicates slowing of nerve conduction
across the distal segment.

### 📌 If Prolonged

Possible Educational Associations

• Carpal Tunnel Syndrome

• Cubital Tunnel Syndrome

• Tarsal Tunnel Syndrome

• Demyelinating Neuropathy

• Chronic Nerve Compression

### 📌 If Normal

Usually indicates preserved distal nerve conduction.

### 📌 If Short

Generally not clinically significant.

### 💡 Interpretation Tip

Interpret together with:

• CMAP Amplitude

• Conduction Velocity

• F-wave
""")

# ---------------- CMAP ---------------- #

with st.expander("🅱️ CMAP Amplitude - Complete Information"):

    st.markdown("""
### ⚡ What is CMAP?

Compound Muscle Action Potential (CMAP) is the electrical response recorded
from a muscle after stimulation of its motor nerve.

### 🎯 Importance

• Reflects functioning motor axons

• Helps differentiate axonal vs demyelinating lesions

• Estimates severity of nerve injury

### 🧠 Clinical Significance

Lower CMAP usually reflects axonal loss.

### 📌 If Reduced

Possible Educational Associations

• Axonal Neuropathy

• Severe Compression Neuropathy

• Peripheral Nerve Injury

• Motor Neuron Disease

• Advanced Diabetic Neuropathy

### 📌 If Normal

Motor axonal function is generally preserved.

### 📌 If Increased

May occur after chronic reinnervation.

### 💡 Interpretation Tip

Never interpret CMAP alone.

Always correlate with

• Distal Latency

• Velocity

• Needle EMG
""")

# ---------------- VELOCITY ---------------- #

with st.expander("🅲 Motor Conduction Velocity - Complete Information"):

    st.markdown("""
### ⚡ What is Conduction Velocity?

Measures the speed of electrical impulse transmission through a motor nerve.

### 🎯 Importance

• Best indicator of myelin health

• Detects demyelination

• Useful for polyneuropathy evaluation

### Typical Normal

Upper Limb

50–65 m/s

Lower Limb

40–55 m/s

### 🧠 Clinical Significance

Reduced velocity indicates slowing of nerve impulse conduction.

### 📌 If Reduced

Possible Educational Associations

• Peripheral Neuropathy

• Demyelinating Neuropathy

• Guillain-Barre Syndrome

• CIDP

• Hereditary Neuropathy

### 📌 If Normal

Usually suggests intact myelin.

### 📌 If Increased

Usually no clinical significance.

### 💡 Interpretation Tip

Cold limbs can artificially reduce conduction velocity.
""")

# ---------------- DURATION ---------------- #

with st.expander("🅳 CMAP Duration - Complete Information"):

    st.markdown("""
### ⚡ What is CMAP Duration?

Represents the total time occupied by the compound muscle action potential.

### 🎯 Importance

• Detects temporal dispersion

• Helps identify demyelination

• Supports interpretation of conduction block

### 🧠 Clinical Significance

Long duration indicates desynchronization of nerve fiber conduction.

### 📌 If Prolonged

Possible Educational Associations

• Demyelinating Neuropathy

• Temporal Dispersion

• Chronic Compression

### 📌 If Normal

Synchronous motor fiber activation.

### 📌 If Short

Usually not clinically significant.

### 💡 Interpretation Tip

Always correlate with latency and conduction velocity.
""")

st.divider()

st.info("""
🧠 **Educational Note**

Motor NCV should never be interpreted using only one parameter.

Accurate interpretation requires correlation between:

• Distal Latency

• CMAP Amplitude

• Conduction Velocity

• CMAP Duration

• Clinical Symptoms

• Needle EMG Findings (when available)

Final interpretation should always be performed by a qualified Neurologist,
Physiatrist, or Electrodiagnostic Physician.
""")
#---------
st.divider()

st.header("⚡ Sensory Nerve Conduction Study (SNCV)")

sensory_nerve = st.selectbox(
    "Select Sensory Nerve",
    [
        "Median Sensory",
        "Ulnar Sensory",
        "Radial Sensory",
        "Sural Nerve",
        "Superficial Peroneal"
    ]
)

col1, col2 = st.columns(2)

with col1:
    sensory_latency = st.number_input(
        "Peak Latency (ms)",
        min_value=0.0,
        value=0.0,
        step=0.1,
        key="sl"
    )

    snap_amplitude = st.number_input(
        "SNAP Amplitude (µV)",
        min_value=0.0,
        value=0.0,
        step=0.1,
        key="sa"
    )

with col2:
    sensory_velocity = st.number_input(
        "Conduction Velocity (m/s)",
        min_value=0.0,
        value=0.0,
        step=0.1,
        key="sv"
    )

st.divider()

with st.expander("🅰️ Peak Latency (Sensory) - Complete Information"):

    st.markdown("""
### ⚡ What is Peak Latency?

Peak latency is the time required for a sensory nerve impulse to travel
from the stimulation point to the recording electrode.

### 🎯 Importance

• Detects distal sensory nerve slowing

• Useful for early entrapment neuropathy

• Sensitive marker of demyelination

### If Prolonged

Possible Educational Associations

• Carpal Tunnel Syndrome

• Cubital Tunnel Syndrome

• Peripheral Neuropathy

• Demyelinating Neuropathy

### If Normal

Usually indicates preserved sensory conduction.

### Clinical Significance

Latency prolongation often represents slowing of the fastest sensory fibers.

### 💡 Tip

Interpret together with SNAP amplitude and conduction velocity.
""")

with st.expander("🅱️ SNAP Amplitude - Complete Information"):

    st.markdown("""
### ⚡ What is SNAP?

Sensory Nerve Action Potential (SNAP) represents the electrical activity
generated by sensory nerve fibers.

### 🎯 Importance

• Reflects sensory axonal integrity

• Estimates severity of sensory nerve damage

### If Reduced

Possible Educational Associations

• Axonal Neuropathy

• Diabetic Neuropathy

• Peripheral Nerve Injury

• Severe Compression

### If Absent

May indicate severe sensory axonal loss.

### Clinical Significance

Reduced SNAP amplitude generally reflects axonal degeneration.

### 💡 Tip

Amplitude alone should never be used for interpretation.
""")

with st.expander("🅲 Sensory Conduction Velocity - Complete Information"):

    st.markdown("""
### ⚡ What is Sensory Conduction Velocity?

Measures the speed of impulse transmission through sensory nerves.

### 🎯 Importance

• Evaluates myelin integrity

• Detects sensory neuropathy

• Useful in generalized polyneuropathy

### Normal

Usually greater than 50 m/s in upper limb nerves.

### If Reduced

Possible Educational Associations

• Demyelinating Neuropathy

• Peripheral Neuropathy

• Diabetic Neuropathy

• Entrapment Neuropathy

### Clinical Significance

Reduced sensory velocity indicates slowing of sensory conduction.

### 💡 Tip

Cold limbs may falsely reduce sensory conduction velocity.
""")

st.divider()

if st.button("Generate Sensory NCV Educational Interpretation"):

    st.subheader("📋 Sensory NCV Summary")

    if sensory_latency > 3.5:
        st.warning("⚠️ Sensory latency is prolonged. Educationally this may indicate distal sensory nerve slowing.")

    else:
        st.success("✅ Sensory latency appears within expected limits.")

    if snap_amplitude < 10:
        st.warning("⚠️ SNAP amplitude is reduced. This may suggest sensory axonal involvement.")

    else:
        st.success("✅ SNAP amplitude appears preserved.")

    if sensory_velocity < 50:
        st.warning("⚠️ Sensory conduction velocity is reduced. Educationally this may indicate demyelination or peripheral neuropathy.")

    else:
        st.success("✅ Sensory conduction velocity appears within expected limits.")

    st.info("""
This interpretation is educational only.

Final interpretation should always be based on:

• Clinical history

• Physical examination

• Complete NCV study

• Needle EMG (when available)

• Physician's opinion
""")
  #--------
st.divider()

st.header("⚡ F-wave Study")

f_wave_latency = st.number_input(
    "F-wave Minimum Latency (ms)",
    min_value=0.0,
    value=0.0,
    step=0.1,
    key="fw_latency"
)

f_wave_status = st.selectbox(
    "F-wave Response",
    [
        "Normal",
        "Prolonged",
        "Absent"
    ],
    key="fw_status"
)

with st.expander("🅳 F-wave - Complete Information"):

    st.markdown("""
### ⚡ What is F-wave?

F-wave is a late motor response produced when an electrical impulse travels
from the stimulation site to the spinal cord and back to the muscle.

### 🎯 Importance

• Evaluates proximal nerve segments

• Detects root lesions

• Detects generalized neuropathy

• Useful in early Guillain-Barre Syndrome

### If Prolonged

Possible Educational Associations

• Demyelinating Neuropathy

• Radiculopathy

• Peripheral Neuropathy

### If Absent

Possible Educational Associations

• Severe Neuropathy

• Guillain-Barre Syndrome

• Proximal Nerve Lesion

### Clinical Significance

F-wave abnormalities usually indicate proximal conduction abnormalities.

### 💡 Tip

Always interpret together with Motor NCV.
""")

st.divider()

st.header("⚡ H-reflex Study")

h_latency = st.number_input(
    "H-reflex Latency (ms)",
    min_value=0.0,
    value=0.0,
    step=0.1,
    key="hreflex_latency"
)

h_status = st.selectbox(
    "H-reflex Response",
    [
        "Normal",
        "Delayed",
        "Absent"
    ],
    key="hreflex_status"
)

with st.expander("🅴 H-reflex - Complete Information"):

    st.markdown("""
### ⚡ What is H-reflex?

The H-reflex is an electrically elicited monosynaptic reflex similar to the
ankle jerk reflex.

### 🎯 Importance

• Evaluates S1 nerve root

• Evaluates tibial nerve

• Useful in radiculopathy

• Useful in polyneuropathy

### If Delayed

Possible Educational Associations

• S1 Radiculopathy

• Tibial Neuropathy

• Peripheral Neuropathy

### If Absent

Possible Educational Associations

• Severe S1 Root Lesion

• Polyneuropathy

• Tibial Nerve Dysfunction

### Clinical Significance

Delayed or absent H-reflex may indicate proximal nerve dysfunction.

### 💡 Tip

Interpret with clinical examination and F-wave findings.
""")

st.divider()

if st.button("Generate Overall NCV Educational Summary"):

    st.subheader("🧠 Overall Educational Interpretation")

    findings = []

    # Motor
    if distal_latency > 4.2:
        findings.append(
            "• Distal latency is prolonged, suggesting slowing across the distal motor nerve segment."
        )

    if cmap < 5:
        findings.append(
            "• CMAP amplitude is reduced, which may indicate motor axonal involvement."
        )

    if velocity < 50:
        findings.append(
            "• Motor conduction velocity is reduced, suggesting possible demyelinating involvement."
        )

    # Sensory
    if sensory_latency > 3.5:
        findings.append(
            "• Sensory latency is prolonged, indicating delayed sensory conduction."
        )

    if snap_amplitude < 10:
        findings.append(
            "• SNAP amplitude is reduced, suggesting sensory axonal involvement."
        )

    if sensory_velocity < 50:
        findings.append(
            "• Sensory conduction velocity is reduced."
        )

    # F-wave
    if f_wave_status == "Prolonged":
        findings.append(
            "• F-wave latency is prolonged, suggesting proximal nerve involvement."
        )

    elif f_wave_status == "Absent":
        findings.append(
            "• F-wave response is absent, which may occur in severe neuropathy or proximal nerve lesions."
        )

    # H-reflex
    if h_status == "Delayed":
        findings.append(
            "• H-reflex is delayed, which may indicate S1 radiculopathy."
        )

    elif h_status == "Absent":
        findings.append(
            "• H-reflex is absent, which may occur in severe S1 root lesions or polyneuropathy."
        )

    if len(findings) == 0:
        st.success(
            "✅ No major educational abnormalities detected from the entered values."
        )

    else:
        for item in findings:
            st.write(item)

    st.divider()

    st.subheader("📚 Possible Educational Associations")

    conditions = []

    if distal_latency > 4.2:
        conditions.append("• Carpal Tunnel Syndrome")
        conditions.append("• Entrapment Neuropathy")

    if velocity < 50:
        conditions.append("• Demyelinating Neuropathy")
        conditions.append("• Chronic Inflammatory Demyelinating Polyneuropathy (CIDP)")
        conditions.append("• Guillain-Barre Syndrome")

    if cmap < 5:
        conditions.append("• Axonal Neuropathy")
        conditions.append("• Peripheral Nerve Injury")

    if snap_amplitude < 10:
        conditions.append("• Sensory Axonal Neuropathy")

    if h_status == "Delayed":
        conditions.append("• S1 Radiculopathy")

    if f_wave_status == "Absent":
        conditions.append("• Proximal Nerve Dysfunction")

    if len(conditions) == 0:
        st.success("No specific educational associations identified.")

    else:
        for c in sorted(set(conditions)):
            st.write(c)

    st.divider()

    st.info("""
⚠️ **Educational Disclaimer**

This NCV Assistant is intended for education and learning purposes only.

It does not diagnose diseases or replace a neurologist, physiatrist,
or electrodiagnostic physician.

Final interpretation should always consider:

• Clinical symptoms

• Physical examination

• Complete NCV study

• Needle EMG findings

• Laboratory investigations (when appropriate)

• Physician's expert opinion
""")
  #---------
# ===========================
# NCV REPORT ANALYSIS
# ===========================

st.divider()

if st.button("🔍 Analyze NCV Report"):

    st.header("🧠 NCV Report Analysis")

    # ------------------------
    # DISTAL LATENCY
    # ------------------------

    if distal_latency > 0:

        if distal_latency <= 4.2:
            st.success(f"✅ Distal Latency : {distal_latency} ms → Normal")

        elif distal_latency <= 5.5:
            st.warning(f"🟡 Distal Latency : {distal_latency} ms → Mildly Prolonged")

        else:
            st.error(f"🔴 Distal Latency : {distal_latency} ms → Significantly Prolonged")


    # ------------------------
    # CMAP
    # ------------------------

    if cmap > 0:

        if cmap >= 5:
            st.success(f"✅ CMAP Amplitude : {cmap} mV → Normal")

        elif cmap >= 2:
            st.warning(f"🟡 CMAP Amplitude : {cmap} mV → Mildly Reduced")

        else:
            st.error(f"🔴 CMAP Amplitude : {cmap} mV → Severely Reduced")


    # ------------------------
    # VELOCITY
    # ------------------------

    if velocity > 0:

        if velocity >= 50:
            st.success(f"✅ Motor Conduction Velocity : {velocity} m/s → Normal")

        elif velocity >= 40:
            st.warning(f"🟡 Motor Conduction Velocity : {velocity} m/s → Mild Slowing")

        else:
            st.error(f"🔴 Motor Conduction Velocity : {velocity} m/s → Significant Slowing")


    # ------------------------
    # SENSORY LATENCY
    # ------------------------

    if sensory_latency > 0:

        if sensory_latency <= 3.5:
            st.success(f"✅ Sensory Latency : {sensory_latency} ms → Normal")

        elif sensory_latency <= 4.5:
            st.warning(f"🟡 Sensory Latency : {sensory_latency} ms → Mildly Prolonged")

        else:
            st.error(f"🔴 Sensory Latency : {sensory_latency} ms → Prolonged")


    # ------------------------
    # SNAP
    # ------------------------

    if snap_amplitude > 0:

        if snap_amplitude >= 10:
            st.success(f"✅ SNAP Amplitude : {snap_amplitude} µV → Normal")

        elif snap_amplitude >= 5:
            st.warning(f"🟡 SNAP Amplitude : {snap_amplitude} µV → Mildly Reduced")

        else:
            st.error(f"🔴 SNAP Amplitude : {snap_amplitude} µV → Severely Reduced")


    # ------------------------
    # SENSORY VELOCITY
    # ------------------------

    if sensory_velocity > 0:

        if sensory_velocity >= 50:
            st.success(f"✅ Sensory Conduction Velocity : {sensory_velocity} m/s → Normal")

        elif sensory_velocity >= 40:
            st.warning(f"🟡 Sensory Conduction Velocity : {sensory_velocity} m/s → Mild Slowing")

        else:
            st.error(f"🔴 Sensory Conduction Velocity : {sensory_velocity} m/s → Significant Slowing")


    # ------------------------
    # F-WAVE
    # ------------------------

    if f_wave_status == "Normal":
        st.success("✅ F-wave → Normal")

    elif f_wave_status == "Prolonged":
        st.warning("🟡 F-wave → Prolonged")

    elif f_wave_status == "Absent":
        st.error("🔴 F-wave → Absent")


    # ------------------------
    # H-REFLEX
    # ------------------------

    if h_status == "Normal":
        st.success("✅ H-reflex → Normal")

    elif h_status == "Delayed":
        st.warning("🟡 H-reflex → Delayed")

    elif h_status == "Absent":
        st.error("🔴 H-reflex → Absent")

    # ===========================
    # OVERALL SUMMARY
    # ===========================

    st.divider()

    st.subheader("🩺 Overall NCV Summary")

    severe = False
    mild = False

    if distal_latency > 5.5:
        severe = True
    elif distal_latency > 4.2:
        mild = True

    if cmap < 2:
        severe = True
    elif cmap < 5:
        mild = True

    if velocity < 40:
        severe = True
    elif velocity < 50:
        mild = True

    if sensory_latency > 4.5:
        severe = True
    elif sensory_latency > 3.5:
        mild = True

    if snap_amplitude < 5:
        severe = True
    elif snap_amplitude < 10:
        mild = True

    if sensory_velocity < 40:
        severe = True
    elif sensory_velocity < 50:
        mild = True

    if f_wave_status == "Absent":
        severe = True
    elif f_wave_status == "Prolonged":
        mild = True

    if h_status == "Absent":
        severe = True
    elif h_status == "Delayed":
        mild = True

    if severe:
        st.error("🔴 Overall Educational Interpretation: Multiple significant NCV abnormalities are present.")
        st.info("Educational possibilities include demyelinating neuropathy, axonal neuropathy, entrapment neuropathy, radiculopathy, or generalized peripheral neuropathy. Correlate with clinical findings and physician interpretation.")

    elif mild:
        st.warning("🟡 Overall Educational Interpretation: Mild NCV abnormalities are present.")
        st.info("These findings may represent early neuropathy, mild entrapment neuropathy, or borderline conduction abnormalities. Clinical correlation is recommended.")

    else:
        st.success("🟢 Overall Educational Interpretation: The entered NCV values are within the common reference ranges.")
        st.info("Normal NCV does not completely exclude neurological disorders. Interpretation should always consider symptoms, examination, and when appropriate, Needle EMG findings.")
    #-------
import streamlit as st

st.set_page_config(
    page_title="EMG Assistant",
    page_icon="💪",
    layout="wide"
)

st.title("💪 Electromyography (EMG) Assistant")

st.warning(
    "⚠️ Educational Tool Only. This assistant does not diagnose diseases. "
    "Interpretation should always be performed by a qualified Neurologist, "
    "Physiatrist or Electrodiagnostic Physician."
)

st.divider()

st.header("💉 Needle EMG Examination")

muscle = st.selectbox(
    "Select Muscle",
    [
        "Abductor Pollicis Brevis (APB)",
        "First Dorsal Interosseous (FDI)",
        "Abductor Digiti Minimi (ADM)",
        "Biceps Brachii",
        "Triceps",
        "Deltoid",
        "Pronator Teres",
        "Extensor Digitorum",
        "Tibialis Anterior",
        "Peroneus Longus",
        "Gastrocnemius",
        "Vastus Medialis",
        "Rectus Femoris",
        "Quadriceps",
        "Hamstrings",
        "Paraspinal Muscles",
        "Other"
    ]
)

st.divider()

st.header("📋 Needle EMG Parameters")

col1, col2 = st.columns(2)

with col1:

    insertional = st.selectbox(
        "Insertional Activity",
        [
            "Normal",
            "Increased",
            "Decreased"
        ]
    )

    fibrillation = st.selectbox(
        "Fibrillation Potentials",
        [
            "Absent",
            "1+",
            "2+",
            "3+",
            "4+"
        ]
    )

    positive_sharp = st.selectbox(
        "Positive Sharp Waves",
        [
            "Absent",
            "1+",
            "2+",
            "3+",
            "4+"
        ]
    )

with col2:

    fasciculation = st.selectbox(
        "Fasciculation Potentials",
        [
            "Absent",
            "Present"
        ]
    )

    crd = st.selectbox(
        "Complex Repetitive Discharges",
        [
            "Absent",
            "Present"
        ]
    )

    myotonic = st.selectbox(
        "Myotonic Discharges",
        [
            "Absent",
            "Present"
        ]
    )

st.divider()

st.header("📈 Motor Unit Action Potential (MUAP)")

col3, col4 = st.columns(2)

with col3:

    muap_amplitude = st.selectbox(
        "MUAP Amplitude",
        [
            "Normal",
            "Small",
            "Large"
        ]
    )

    muap_duration = st.selectbox(
        "MUAP Duration",
        [
            "Normal",
            "Short",
            "Long"
        ]
    )

with col4:

    polyphasic = st.selectbox(
        "Polyphasic Potentials",
        [
            "Absent",
            "Present"
        ]
    )

    recruitment = st.selectbox(
        "Recruitment Pattern",
        [
            "Normal",
            "Reduced",
            "Early",
            "Discrete",
            "Absent"
        ]
    )

st.divider()

st.header("📊 Interference Pattern")

interference = st.selectbox(
    "Interference Pattern",
    [
        "Normal",
        "Reduced",
        "Incomplete",
        "Full"
    ]
)

st.divider()

st.info("""
💡 **Educational Note**

Needle EMG evaluates:

• Muscle membrane stability

• Active denervation

• Chronic reinnervation

• Myopathic disorders

• Neurogenic disorders

Interpretation should always be correlated with:

• Clinical examination

• Nerve Conduction Study (NCV)

• Medical history

• Imaging and laboratory investigations when appropriate.
""")
#------
st.divider()

st.header("📚 Needle EMG Parameter Information")

# ---------------------------------------------------------
# INSERTIONAL ACTIVITY
# ---------------------------------------------------------

with st.expander("🅰️ Insertional Activity - Code: EMG_INS_01"):

    st.markdown("""
### 💉 What is Insertional Activity?

Insertional activity is the brief electrical activity generated when the EMG needle is inserted into a muscle.

### 🎯 Importance

• Assesses muscle membrane stability

• Detects muscle fiber irritation

• Helps identify denervation

### Normal Finding

Brief activity lasting less than 300 milliseconds.

### If Increased

Possible Educational Associations

• Acute Denervation

• Inflammatory Myopathy

• Muscle Irritation

• Radiculopathy

### If Decreased

Possible Educational Associations

• Fibrosis

• Fatty Muscle Replacement

• Chronic Muscle Disease

### 🩺 Clinical Significance

Abnormal insertional activity often reflects muscle membrane instability.

### 💡 Interpretation Tip

Interpret together with spontaneous activity and MUAP findings.
""")

# ---------------------------------------------------------
# FIBRILLATION POTENTIALS
# ---------------------------------------------------------

with st.expander("🅱️ Fibrillation Potentials - Code: EMG_FIB_02"):

    st.markdown("""
### 💉 What are Fibrillation Potentials?

Fibrillation potentials are spontaneous discharges from single muscle fibers.

### 🎯 Importance

One of the most important signs of active denervation.

### Normal Finding

Absent

### If Present

Possible Educational Associations

• Peripheral Neuropathy

• Radiculopathy

• Motor Neuron Disease

• Nerve Injury

• Severe Axonal Neuropathy

### Clinical Significance

Indicates active denervation of muscle fibers.

### Grading

1+ = Few

2+ = Mild

3+ = Moderate

4+ = Severe

### 💡 Interpretation Tip

Always correlate with Positive Sharp Waves.
""")

# ---------------------------------------------------------
# POSITIVE SHARP WAVES
# ---------------------------------------------------------

with st.expander("🅲 Positive Sharp Waves - Code: EMG_PSW_03"):

    st.markdown("""
### 💉 What are Positive Sharp Waves?

Positive Sharp Waves are spontaneous muscle fiber discharges similar to fibrillation potentials.

### 🎯 Importance

Represents muscle denervation.

### Normal Finding

Absent

### If Present

Possible Educational Associations

• Radiculopathy

• Peripheral Nerve Injury

• Motor Neuron Disease

• Chronic Denervation

### Clinical Significance

Suggests unstable muscle membrane due to denervation.

### Grading

1+ = Mild

2+ = Moderate

3+ = Marked

4+ = Severe

### 💡 Interpretation Tip

Interpret together with Fibrillation Potentials.
""")

# ---------------------------------------------------------
# FASCICULATION POTENTIALS
# ---------------------------------------------------------

with st.expander("🅳 Fasciculation Potentials - Code: EMG_FASC_04"):

    st.markdown("""
### 💉 What are Fasciculation Potentials?

Spontaneous discharges of an entire motor unit.

### 🎯 Importance

May occur in both normal individuals and neurological disorders.

### Normal Finding

Absent

### If Present

Possible Educational Associations

• Benign Fasciculation Syndrome

• Motor Neuron Disease

• Peripheral Neuropathy

• Radiculopathy

### Clinical Significance

Should always be interpreted with other EMG abnormalities.

### 💡 Interpretation Tip

Fasciculations alone are not diagnostic.
""")
    #------
# ---------------------------------------------------------
# COMPLEX REPETITIVE DISCHARGES (CRD)
# ---------------------------------------------------------

with st.expander("🅴 Complex Repetitive Discharges (CRD) - Code: EMG_CRD_05"):

    st.markdown("""
### 💉 What are Complex Repetitive Discharges (CRDs)?

CRDs are repetitive spontaneous muscle discharges generated by groups of muscle fibers.

### 🎯 Importance

• Indicates chronic muscle pathology

• Suggests long-standing denervation or myopathy

### Normal Finding

Absent

### If Present

Possible Educational Associations

• Chronic Neuropathy

• Chronic Radiculopathy

• Myopathy

• Previous Nerve Injury

### 🩺 Clinical Significance

Usually represents chronic rather than acute disease.

### 💡 Interpretation Tip

Interpret with MUAP duration and recruitment pattern.
""")

# ---------------------------------------------------------
# MYOTONIC DISCHARGES
# ---------------------------------------------------------

with st.expander("🅵 Myotonic Discharges - Code: EMG_MYO_06"):

    st.markdown("""
### 💉 What are Myotonic Discharges?

Myotonic discharges are spontaneous waxing and waning electrical discharges
producing the classic 'dive bomber' sound on EMG.

### 🎯 Importance

Characteristic finding in myotonic disorders.

### Normal Finding

Absent

### If Present

Possible Educational Associations

• Myotonic Dystrophy

• Myotonia Congenita

• Channelopathies

### 🩺 Clinical Significance

Highly suggestive of myotonic muscle disorders.

### 💡 Interpretation Tip

Always correlate with clinical symptoms.
""")

# ---------------------------------------------------------
# MUAP AMPLITUDE
# ---------------------------------------------------------

with st.expander("🅶 MUAP Amplitude - Code: EMG_MUAP_07"):

    st.markdown("""
### 💉 What is MUAP Amplitude?

Motor Unit Action Potential (MUAP) amplitude reflects the size of the motor unit.

### 🎯 Importance

Evaluates chronic denervation and reinnervation.

### Normal Finding

Normal amplitude according to muscle examined.

### If Increased

Possible Educational Associations

• Chronic Neurogenic Disorder

• Reinnervation

• Motor Neuron Disease

### If Decreased

Possible Educational Associations

• Myopathy

• Muscle Fiber Loss

### 🩺 Clinical Significance

Large amplitudes suggest chronic neurogenic change.
Small amplitudes suggest myopathic change.

### 💡 Interpretation Tip

Interpret together with duration and recruitment.
""")

# ---------------------------------------------------------
# MUAP DURATION
# ---------------------------------------------------------

with st.expander("🅷 MUAP Duration - Code: EMG_MUAP_08"):

    st.markdown("""
### 💉 What is MUAP Duration?

Represents the time occupied by one motor unit action potential.

### 🎯 Importance

Helps distinguish neurogenic and myopathic disorders.

### Normal Finding

Normal duration for the selected muscle.

### If Increased

Possible Educational Associations

• Chronic Neurogenic Lesion

• Reinnervation

### If Decreased

Possible Educational Associations

• Myopathy

### 🩺 Clinical Significance

Long duration suggests chronic denervation.
Short duration suggests myopathy.

### 💡 Interpretation Tip

Always correlate with MUAP amplitude.
""")

# ---------------------------------------------------------
# POLYPHASIC POTENTIALS
# ---------------------------------------------------------

with st.expander("🅸 Polyphasic Potentials - Code: EMG_POLY_09"):

    st.markdown("""
### 💉 What are Polyphasic Potentials?

Motor unit action potentials having more than four phases.

### 🎯 Importance

May indicate reinnervation or myopathic change.

### Normal Finding

Few polyphasic potentials may be normal.

### If Increased

Possible Educational Associations

• Chronic Neuropathy

• Reinnervation

• Myopathy

### 🩺 Clinical Significance

Increased polyphasic potentials indicate motor unit remodeling.

### 💡 Interpretation Tip

Interpret with MUAP amplitude and duration.
""")

# ---------------------------------------------------------
# RECRUITMENT PATTERN
# ---------------------------------------------------------

with st.expander("🅹 Recruitment Pattern - Code: EMG_REC_10"):

    st.markdown("""
### 💉 What is Recruitment Pattern?

Recruitment describes how motor units are activated during voluntary contraction.

### 🎯 Importance

Essential for differentiating neurogenic and myopathic disorders.

### Normal Finding

Normal recruitment.

### Reduced Recruitment

Possible Educational Associations

• Peripheral Neuropathy

• Radiculopathy

• Motor Neuron Disease

### Early Recruitment

Possible Educational Associations

• Myopathy

### Absent Recruitment

Possible Educational Associations

• Complete Denervation

• Severe Nerve Injury

### 🩺 Clinical Significance

Reduced recruitment usually suggests neurogenic pathology.

### 💡 Interpretation Tip

Interpret with interference pattern.
""")

# ---------------------------------------------------------
# INTERFERENCE PATTERN
# ---------------------------------------------------------

with st.expander("🅺 Interference Pattern - Code: EMG_INT_11"):

    st.markdown("""
### 💉 What is Interference Pattern?

Represents the overall electrical activity during maximal voluntary contraction.

### 🎯 Importance

Evaluates functional muscle activation.

### Normal Finding

Full interference pattern.

### Reduced Pattern

Possible Educational Associations

• Neurogenic Disorder

• Severe Weakness

### Early Full Pattern

Possible Educational Associations

• Myopathy

### 🩺 Clinical Significance

Reduced interference generally reflects loss of functioning motor units.

### 💡 Interpretation Tip

Interpret with recruitment pattern and MUAP findings.
""")

st.divider()

st.info("""
📘 **Educational Note**

Needle EMG interpretation should **never rely on a single parameter**.

A proper educational interpretation considers:

• Insertional Activity
• Fibrillation Potentials
• Positive Sharp Waves
• Fasciculations
• CRDs
• Myotonic Discharges
• MUAP Amplitude
• MUAP Duration
• Polyphasic Potentials
• Recruitment Pattern
• Interference Pattern

All findings should be interpreted together with the patient's clinical history, neurological examination, and NCV results.
""")
#------

# ===========================================================
# EMG REPORT ANALYSIS
# ===========================================================

st.divider()

if st.button("🔍 Analyze EMG Report"):

    st.header("💪 Needle EMG Report Analysis")

    neurogenic = 0
    myopathic = 0
    chronic = 0

    # ------------------------------------------------------
    # INSERTIONAL ACTIVITY
    # ------------------------------------------------------

    if insertional == "Normal":
        st.success("✅ Insertional Activity → Normal")

    elif insertional == "Increased":
        st.warning("🟡 Insertional Activity → Increased")
        st.write("""
Possible Educational Significance

• Active Denervation

• Radiculopathy

• Inflammatory Myopathy

• Muscle Membrane Irritation
""")
        neurogenic += 1

    else:
        st.error("🔴 Insertional Activity → Decreased")
        st.write("""
Possible Educational Significance

• Fibrosis

• Fatty Muscle Replacement

• Chronic Muscle Disease
""")
        chronic += 1


    # ------------------------------------------------------
    # FIBRILLATION
    # ------------------------------------------------------

    if fibrillation == "Absent":
        st.success("✅ Fibrillation Potentials → Absent")

    else:
        st.error(f"🔴 Fibrillation Potentials → {fibrillation}")

        st.write("""
Educational Interpretation

Presence of fibrillation potentials usually indicates active denervation.

Possible Associations

• Peripheral Neuropathy

• Radiculopathy

• Axonal Injury

• Motor Neuron Disease
""")
        neurogenic += 2


    # ------------------------------------------------------
    # POSITIVE SHARP WAVES
    # ------------------------------------------------------

    if positive_sharp == "Absent":
        st.success("✅ Positive Sharp Waves → Absent")

    else:
        st.error(f"🔴 Positive Sharp Waves → {positive_sharp}")

        st.write("""
Educational Interpretation

Positive sharp waves suggest unstable muscle membrane.

Possible Associations

• Active Denervation

• Radiculopathy

• Peripheral Nerve Injury
""")
        neurogenic += 2


    # ------------------------------------------------------
    # FASCICULATION
    # ------------------------------------------------------

    if fasciculation == "Absent":
        st.success("✅ Fasciculation Potentials → Absent")

    else:
        st.warning("🟡 Fasciculation Potentials → Present")

        st.write("""
Possible Educational Associations

• Benign Fasciculation Syndrome

• Motor Neuron Disease

• Peripheral Neuropathy
""")
        neurogenic += 1


    # ------------------------------------------------------
    # CRD
    # ------------------------------------------------------

    if crd == "Absent":
        st.success("✅ Complex Repetitive Discharges → Absent")

    else:
        st.warning("🟡 Complex Repetitive Discharges → Present")

        st.write("""
Possible Educational Associations

• Chronic Radiculopathy

• Chronic Neuropathy

• Previous Nerve Injury
""")
        chronic += 2


    # ------------------------------------------------------
    # MYOTONIC
    # ------------------------------------------------------

    if myotonic == "Absent":
        st.success("✅ Myotonic Discharges → Absent")

    else:
        st.error("🔴 Myotonic Discharges → Present")

        st.write("""
Possible Educational Associations

• Myotonic Dystrophy

• Myotonia Congenita

• Channelopathy
""")
        myopathic += 2


    st.divider()

    st.header("📈 MUAP Analysis")
#----------
    # ------------------------------------------------------
    # MUAP AMPLITUDE
    # ------------------------------------------------------

    if muap_amplitude == "Normal":
        st.success("✅ MUAP Amplitude → Normal")

    elif muap_amplitude == "Large":
        st.warning("🟡 MUAP Amplitude → Large")

        st.write("""
Educational Interpretation

Large MUAPs usually indicate chronic reinnervation.

Possible Educational Associations

• Chronic Neurogenic Disorder

• Motor Neuron Disease

• Old Peripheral Nerve Injury

• Chronic Radiculopathy
""")
        neurogenic += 2
        chronic += 1

    elif muap_amplitude == "Small":
        st.warning("🟡 MUAP Amplitude → Small")

        st.write("""
Educational Interpretation

Small MUAPs are commonly associated with myopathic disorders.

Possible Educational Associations

• Myopathy

• Muscular Dystrophy

• Inflammatory Myopathy
""")
        myopathic += 2


    # ------------------------------------------------------
    # MUAP DURATION
    # ------------------------------------------------------

    if muap_duration == "Normal":
        st.success("✅ MUAP Duration → Normal")

    elif muap_duration == "Long":
        st.warning("🟡 MUAP Duration → Long")

        st.write("""
Educational Interpretation

Long duration MUAPs usually indicate chronic denervation and reinnervation.

Possible Educational Associations

• Chronic Radiculopathy

• Peripheral Neuropathy

• Motor Neuron Disease
""")
        neurogenic += 2
        chronic += 1

    elif muap_duration == "Short":
        st.warning("🟡 MUAP Duration → Short")

        st.write("""
Educational Interpretation

Short duration MUAPs commonly suggest myopathic disorders.

Possible Educational Associations

• Myopathy

• Muscle Fiber Disease
""")
        myopathic += 2


    # ------------------------------------------------------
    # POLYPHASIC POTENTIALS
    # ------------------------------------------------------

    if polyphasic == "Absent":
        st.success("✅ Polyphasic Potentials → Absent")

    else:
        st.warning("🟡 Polyphasic Potentials → Present")

        st.write("""
Educational Interpretation

Polyphasic MUAPs indicate remodeling of motor units.

Possible Educational Associations

• Chronic Reinnervation

• Peripheral Neuropathy

• Myopathy
""")

        neurogenic += 1
        myopathic += 1


    # ------------------------------------------------------
    # RECRUITMENT
    # ------------------------------------------------------

    if recruitment == "Normal":
        st.success("✅ Recruitment Pattern → Normal")

    elif recruitment == "Reduced":
        st.warning("🟡 Recruitment Pattern → Reduced")

        st.write("""
Possible Educational Associations

• Peripheral Neuropathy

• Radiculopathy

• Motor Neuron Disease
""")

        neurogenic += 2

    elif recruitment == "Early":
        st.warning("🟡 Recruitment Pattern → Early")

        st.write("""
Possible Educational Associations

• Myopathy

• Inflammatory Muscle Disease
""")

        myopathic += 2

    elif recruitment == "Discrete":
        st.error("🔴 Recruitment Pattern → Discrete")

        st.write("""
Possible Educational Associations

• Severe Neurogenic Lesion

• Chronic Denervation
""")

        neurogenic += 3

    elif recruitment == "Absent":
        st.error("🔴 Recruitment Pattern → Absent")

        st.write("""
Possible Educational Associations

• Complete Denervation

• Severe Nerve Injury
""")

        neurogenic += 4


    # ------------------------------------------------------
    # INTERFERENCE PATTERN
    # ------------------------------------------------------

    if interference == "Normal":
        st.success("✅ Interference Pattern → Normal")

    elif interference == "Reduced":
        st.warning("🟡 Interference Pattern → Reduced")

        st.write("""
Possible Educational Associations

• Neurogenic Disorder

• Severe Weakness

• Peripheral Neuropathy
""")

        neurogenic += 2

    elif interference == "Incomplete":
        st.warning("🟡 Interference Pattern → Incomplete")

        st.write("""
Possible Educational Associations

• Partial Motor Unit Loss

• Chronic Neurogenic Disorder
""")

        neurogenic += 2

    elif interference == "Full":
        st.warning("🟡 Full Interference Pattern")

        st.write("""
Possible Educational Associations

• Myopathy

• Early Muscle Disease
""")

        myopathic += 2

    st.divider()

    st.header("🩺 Overall EMG Summary")
#-------
